version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    restart: unless-stopped
    env_file: .env.production
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi

  postgres:
    image: postgres:15
    container_name: strapi-postgres
    restart: unless-stopped
    env_file: .env.production
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data
    networks:
      - strapi

  nginx:
    image: nginx:alpine
    container_name: strapi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public/uploads:/var/www/uploads
    depends_on:
      - strapi
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge
